apiVersion: 1

# liste des sources de données qui doivent être supprimées de la base de données
deleteDatasources:
  - name: Prometheus
    orgId: 1

# liste des sources de données à insérer/mettre à jour en fonction de ce qui est disponible dans la base de données
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true
