name: Train Model and Log to MLflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --dev

      - name: Pull data with DVC
        run: uv run dvc pull

      - name: Train model and log to MLflow
        run: uv run src/models/train_model.py
        env:
          MLFLOW_TRACKING_USERNAME: MaxVigne
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
